# Serviço do front-end

services:
  backend:
    build: ./backend       
    container_name: avaliacao-backend
    ports:
      - "8080:8080"
    restart: always

  # Serviço do Frontend
  frontend:
    build: ./frontend     
    container_name: avaliacao-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend            
    restart: always